# Generated by Django 4.2.9 on 2026-02-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
    ]
