# Generated by Django 4.2.9 on 2026-02-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_service_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
