import os

# Frontend origin used to build absolute image URLs. Set FRONTEND_URL in
# `backend/.env` if your frontend runs on a different host/port.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://127.0.0.1:8000').rstrip('/')

products = [
    {
        "_id": "1",
        "name": "Banana Whale Plush",
        "image": f"{FRONTEND_URL}/images/Banana Whale.jpg",
        "description": "Handmade crochet banana whale — soft, cute, and perfect as a gift.",
        "category": "plushies",
        "price": 60,
        "countInStock": 5,
        "rating": 4.5,
        "numReviews": 10,
    },
    {
        "_id": "2",
        "name": "Bocchi",
        "image": f"{FRONTEND_URL}/images/Bocchi.jpg",
        "description": "Cute Bocchi-inspired crochet doll — collectible and lovingly stitched.",
        "category": "plushies",
        "price": 350,
        "countInStock": 4,
        "rating": 4.7,
        "numReviews": 8,
    },
    {
        "_id": "3",
        "name": "Crochet Doll - Style 1",
        "image": f"{FRONTEND_URL}/images/Crochet Doll.jpg",
        "description": "Handcrafted crochet doll with detailed clothing and soft stuffing.",
        "category": "plushies",
        "price": 450,
        "countInStock": 6,
        "rating": 4.9,
        "numReviews": 14,
    },
    {
        "_id": "4",
        "name": "Crochet Doll - Style 2",
        "image": f"{FRONTEND_URL}/images/CrochetDoll2.jpg",
        "description": "A second style of crochet doll — charming and unique.",
        "category": "plushies",
        "price": 450,
        "countInStock": 3,
        "rating": 4.6,
        "numReviews": 6,
    },
    {
        "_id": "5",
        "name": "Hearts Ornament",
        "image": f"{FRONTEND_URL}/images/Hearts.jpg",
        "description": "Small heart ornaments — great for decorations and gifts.",
        "category": "keychains",
        "price": 50,
        "countInStock": 15,
        "rating": 4.5,
        "numReviews": 5,
    },
    {
        "_id": "6",
        "name": "Lotus Flower",
        "image": f"{FRONTEND_URL}/images/Lotus.jpg",
        "description": "Delicate crochet lotus — perfect for display or photography props.",
        "category": "flowers",
        "price": 450,
        "countInStock": 7,
        "rating": 4.4,
        "numReviews": 4,
    },
    {
        "_id": "7",
        "name": "Penguin Plush",
        "image": f"{FRONTEND_URL}/images/Penguin.jpg",
        "description": "Adorable crochet penguin toy — soft and kid-friendly.",
        "category": "plushies",
        "price": 110,
        "countInStock": 9,
        "rating": 4.8,
        "numReviews": 11,
    },
    {
        "_id": "8",
        "name": "Roses Bouquet",
        "image": f"{FRONTEND_URL}/images/Roses.jpg",
        "description": "Crochet roses bouquet — everlasting floral decoration.",
        "category": "flowers",
        "price": 400,
        "countInStock": 2,
        "rating": 4.9,
        "numReviews": 9,
    },
    {
        "_id": "9",
        "name": "Sunflowers",
        "image": f"{FRONTEND_URL}/images/Sunflowers.jpg",
        "description": "Bright crochet sunflowers — cheerful home accent pieces.",
        "category": "flowers",
        "price": 450,
        "countInStock": 8,
        "rating": 4.7,
        "numReviews": 7,
    },
    {
        "_id": "10",
        "name": "Tulips",
        "image": f"{FRONTEND_URL}/images/Tulips.jpg",
        "description": "Set of crochet tulips — colorful and reusable.",
        "category": "flowers",
        "price": 350,
        "countInStock": 10,
        "rating": 4.6,
        "numReviews": 6,
    },
]
